### ISSUE TITLE
OSM Attribution requirement

### ISSUE THREAD

**Issue by inan-hira** [EDJNet/OlympicsGoNUTS#1]
Hi,

I just saw your beautiful map at https://edjnet.github.io/OlympicsGoNUTS. Great idea, and simple application.

I noticed the map uses Carto basemap tiles, which are generated using OpenStreetMap data.

There's one important requirement for using the OSM data. While the OpenStreetMap data is free to use, you must give proper attribution as described in the Attribution Guidelines:

> OpenStreetMap (OSM) data is distributed under the Open Database License (ODbL). If you want to use OpenStreetMap data in something you create and distribute, you must attribute OpenStreetMap[^1].

This is also mentioned in Carto's Terms and Conditions[^2]. You can see how Carto gives attribution at https://basemaps.cartocdn.com/.

I can see that you are using Leaflet JS library to handle the map display. Leaflet makes it very easy to give attribution.

Could you please follow the guide and add proper credits? Thank you very much.

[^1]: https://osmfoundation.org/wiki/Licence/Attribution_Guidelines#OpenStreetMap_Attribution_Guideline
[^2]: https://drive.google.com/file/d/15W7lHI9LcRKsUCuWgOCWkVwB54HHV5kb/view

**Comment by giocomai** [comment]
Hi, thanks for bringing this up!

I'll be adding attribution as suggested in the [Carto basemap repo](https://github.com/CartoDB/basemap-styles). 

Re-rendering the files and will upload later today.
